name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4.3.0

    - name: install luarocks deps
      run: |
        luarocks install tl

    - name: install make deps
      run: |
        apt install fd

    - name: make
      run: make build doc

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        path: |
          build/doc/cluttex_teal.pdf
          bin/cluttex_teal*
