-- SPDX-FileCopyrightText: 2024 - 2025 Lukas Heindl
--
-- SPDX-License-Identifier: GPL-3.0-or-later

name: nightly build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install make deps
      run: |
        sudo apt-get install fd-find

    - uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: |
          scheme-basic
          l3build
          catppuccinpalette
          tcolorbox
          koma-script
          luatex
          microtype
          todo
          csquotes
          pdflscape
          cleveref
          tools
          booktabs
          listings
          tikzfill
          marginnote
          pgfopts
          xcolor

    - name: Install lua
      uses: jkl1337/gh-actions-lua@v11
      with:
        luaVersion: "5.4.7"
    - name: Install LuaRocks (latest)
      uses: jkl1337/gh-actions-luarocks@v5

    - name: install luarocks deps
      run: |
        luarocks install --dev tl
        luarocks install cyan
        luarocks install lester

    - name: make
      run: make FD=fdfind build doc

    - name: move artifacts
      run: |
          mv build/doc/cluttealtex.pdf ./
          mv bin/cluttealtex* ./

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: doc
        path: |
          cluttealtex.pdf

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: binaries
        path: |
          cluttealtex
          cluttealtex.bat
