# SPDX-FileCopyrightText: 2024 - 2025 Lukas Heindl
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Releases

on: 
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: install make deps
      run: |
        sudo apt-get install fd-find

    - uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: |
          scheme-basic
          l3build
          catppuccinpalette
          tcolorbox
          koma-script
          luatex
          microtype
          todo
          csquotes
          pdflscape
          cleveref
          tools
          booktabs
          listings
          tikzfill
          marginnote
          pgfopts
          xcolor

    - name: Install lua
      uses: jkl1337/gh-actions-lua@v11
      with:
        luaVersion: "5.4.7"
    - name: Install LuaRocks (latest)
      uses: jkl1337/gh-actions-luarocks@v5

    - name: install luarocks deps
      run: |
        luarocks install --dev tl
        luarocks install cyan

    - name: make
      run: make FD=fdfind build doc

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/doc/cluttealtex.pdf,bin/cluttealtex*"
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
